AWSTemplateFormatVersion: "2010-09-09"
Description: Reset API for SBS

Parameters:
  ResourcePrefix:
    Type: String
    MinLength: '2'

Resources:
  GatewayLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile:
          "Fn::Sub": |
            import json
            import logging
            logging.basicConfig()
            logger = logging.getLogger(__name__)
            logger.setLevel(logging.INFO)

            def handler(event, context):
                logger.info('Event: ' + json.dumps(event))
                logger.info('Context: ' + str(dir(context)))
                return {'sbs-keg-reset': event}

      Description: A sbs-keg-reset function
      Handler: index.handler
      Role:
        "Fn::GetAtt": [LambdaExecutionRole, Arn]
      Runtime: python2.7

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
            Action: ["sts:AssumeRole"]
      Policies:
        - PolicyName: LambdaRole
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "arn:aws:logs:*:*:*"
      # ManagedPolicyArns: ["arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"]

  GatewayApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name:
        "Fn::Join":
          - "-"
          - - { Ref: ResourcePrefix }
            - "API"
      Description: API used for Gateway requests
      FailOnWarnings: true

  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      FunctionName:
        "Fn::GetAtt": [GatewayLambda, Arn]
      Principal: apigateway.amazonaws.com
      SourceArn:
        "Fn::Join":
          - ""
          - - "arn:aws:execute-api:"
            - { Ref: "AWS::Region" }
            - ":"
            - { Ref: "AWS::AccountId" }
            - ":"
            - { Ref: "GatewayApi" }
            - "/*"

  ApiGatewayCloudWatchLogsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal:
            Service: [apigateway.amazonaws.com]
          Action: ["sts:AssumeRole"]
      Policies:
      - PolicyName: ApiGatewayLogsPolicy
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: Allow
            Action:
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:DescribeLogGroups"
              - "logs:DescribeLogStreams"
              - "logs:PutLogEvents"
              - "logs:GetLogEvents"
              - "logs:FilterLogEvents"
            Resource: "*"

  ApiGatewayAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        "Fn::GetAtt": [ApiGatewayCloudWatchLogsRole, Arn]

  GatewayApiStage:
    DependsOn: [ApiGatewayAccount]
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId: { Ref: "ApiDeployment" }
      MethodSettings:
      - DataTraceEnabled: true
        HttpMethod: "*"
        LoggingLevel: INFO
        ResourcePath: /*
      RestApiId: { Ref: "GatewayApi" }
      StageName: LATEST

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: [GatewayRequest]
    Properties:
      RestApiId: { Ref: "GatewayApi" }
      StageName: DummyStage

  MyResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: { Ref: "GatewayApi" }
      ParentId:
        "Fn::GetAtt": [GatewayApi, RootResourceId]
      # PathPart: "{proxy+}"
      PathPart: sbs-keg-reset

  KegResetModel:
    Type: AWS::ApiGateway::Model
    Properties:
      RestApiId: { Ref: "GatewayApi" }
      ContentType: "application/json"
      Description: "SBS Keg Reset Schema"
      Name: SbsKegReset
      Schema:
        "$schema": "http://json-schema.org/draft-04/schema#"
        title: SbsKegResetSchema
        type: object
        properties:
          keg_capacity_liters:
            type: number
          beer_name:
            type: string
          beer_brewery:
            type: string
          beer_description:
            type: string
        required: [keg_capacity_liters, beer_name, beer_brewery, beer_description]

  RequestValidator:
    Type: "AWS::ApiGateway::RequestValidator"
    Properties:
      Name: SbsConformanceValidator
      RestApiId: { Ref: "GatewayApi" }
      ValidateRequestBody: "true"
      ValidateRequestParameters: "false"


  GatewayRequest:
    DependsOn: LambdaPermission
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: POST
      Integration:
        Type: AWS
        IntegrationHttpMethod: POST
        Uri:
          "Fn::Join":
            - ""
            - - "arn:aws:apigateway:"
              - { Ref: "AWS::Region" }
              - ":lambda:path/2015-03-31/functions/"
              - "Fn::GetAtt": [GatewayLambda, Arn]
              - "/invocations"
        IntegrationResponses:
        - StatusCode: 200
      RequestModels:
        "application/json": { Ref: KegResetModel }
      ResourceId: { Ref: "MyResource" }
      RestApiId: { Ref: "GatewayApi" }
      MethodResponses:
      - StatusCode: 200

Outputs:
  RootUrl:
    Description: Root URL of the API gateway
    Value:
      "Fn::Join":
        - ""
        - - "https://"
          - { Ref: "GatewayApi" }
          - .execute-api.
          - { Ref: "AWS::Region" }
          - ".amazonaws.com"

  CurlCommand:
    Description: Curl command for the endpoint
    Value:
      "Fn::Join":
        - ""
        - - 'curl -H "Content-Type: application/json" -H "Accept: application/json" '
          - '-X POST -d ''{"keg_capacity_liters":20, "beer_name":"Blanche de Chambly", "beer_brewery": "Unibroue", "beer_description": "Glorious."}'' '
          - "https://"
          - { Ref: "GatewayApi" }
          - .execute-api.
          - { Ref: "AWS::Region" }
          - ".amazonaws.com"
          - "/LATEST/sbs-keg-reset"
